import { Pharmacy, ScrapedPharmacyResult } from '../types/index.js';

export const DEMO_PHARMACIES: ScrapedPharmacyResult[] = [
  {
    name: "Pharmacie de Bingerville",
    phone: "+225 27 22 40 31 12",
    secondaryPhone: "+225 07 08 12 34 56",
    email: "contact@pharmaciebingerville.ci",
    address: "Centre-Ville, Face au Grand Marché Municipal, Rue Principale",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.358210,
    longitude: -3.886450,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/bingerville-centre",
    gardeStatus: "confirme",
    gardeStart: "2026-09-08T08:00:00Z",
    gardeEnd: "2026-09-15T08:00:00Z",
    notes: "[DEMO] Donnée de démonstration fictive — De garde 24h/24 cette semaine",
  },
  {
    name: "Pharmacie Feh Kessé",
    phone: "+225 27 22 40 89 74",
    secondaryPhone: "+225 05 45 67 89 01",
    email: "pharmaciefehkesse@gmail.com",
    address: "Carrefour Feh Kessé, Voie Principale vers Abatta",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.371420,
    longitude: -3.914580,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/feh-kesse",
    gardeStatus: "non_confirme",
    notes: "[DEMO] Donnée de démonstration fictive — Officine de quartier ouverte 7h30-21h",
  },
  {
    name: "Pharmacie Blanche de Bingerville",
    phone: "+225 07 09 88 77 66",
    secondaryPhone: null,
    email: "info@pharmacieblanche-ci.org",
    address: "Carrefour Safari, Axe Bingerville-Abidjan",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.366300,
    longitude: -3.899200,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/blanche",
    gardeStatus: "confirme",
    gardeStart: "2026-09-10T20:00:00Z",
    gardeEnd: "2026-09-17T08:00:00Z",
    notes: "[DEMO] Donnée de démonstration fictive — Pharmacie de garde de nuit confirmée",
  },
  {
    name: "Pharmacie Savane",
    phone: "+225 27 22 40 55 22",
    secondaryPhone: "+225 01 02 03 04 05",
    email: null, // Non disponible
    address: "Quartier Savane 1, Carrefour CME, Bingerville",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.362150,
    longitude: -3.881240,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/savane",
    gardeStatus: "non_confirme",
    notes: "[DEMO] Donnée de démonstration fictive — Email non disponible publiquement",
  },
  {
    name: "Pharmacie Bel Horizon",
    phone: "+225 07 77 11 22 33",
    secondaryPhone: null,
    email: "belhorizon.pharma@aviso.ci",
    address: "Cité Bel Horizon, Entrée Principale, Bingerville",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.378900,
    longitude: -3.905410,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/bel-horizon",
    gardeStatus: "confirme",
    gardeStart: "2026-09-12T08:00:00Z",
    gardeEnd: "2026-09-19T08:00:00Z",
    notes: "[DEMO] Donnée de démonstration fictive — Service de garde continu",
  },
  {
    name: "Pharmacie Ephrata",
    phone: "+225 25 22 00 11 44",
    secondaryPhone: null,
    email: null,
    address: "Route de l'Ananeraie, Près du Collège Moderne",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.354110,
    longitude: -3.876500,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/ephrata",
    gardeStatus: "non_confirme",
    notes: "[DEMO] Donnée de démonstration fictive — En attente de publication du tour de garde",
  },
  {
    name: "Pharmacie de la Mairie",
    phone: "+225 05 05 99 88 77",
    secondaryPhone: "+225 27 22 40 10 20",
    email: "mairie.pharma.bingerville@gmail.com",
    address: "Boulevard de l'Hôtel de Ville, Face aux Services Techniques",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.359800,
    longitude: -3.889100,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/mairie",
    gardeStatus: "confirme",
    gardeStart: "2026-09-05T08:00:00Z",
    gardeEnd: "2026-09-12T08:00:00Z",
    notes: "[DEMO] Donnée de démonstration fictive — Garde diurne et nocturne",
  },
  {
    name: "Pharmacie Saint Paul Gbagba",
    phone: "+225 07 48 20 30 40",
    secondaryPhone: null,
    email: null,
    address: "Quartier Gbagba Extension, Rue des Écoles",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.368500,
    longitude: -3.872300,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/saint-paul",
    gardeStatus: "inconnu",
    notes: "[DEMO] Donnée de démonstration fictive — Statut de garde non confirmé",
  },
  {
    name: "Pharmacie des Lagunes",
    phone: "+225 27 22 40 77 00",
    secondaryPhone: null,
    email: "contact@pharmacie-lagunes.ci",
    address: "Quartier Résidentiel Marina, Voie Lagune Ébrié",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: 5.347800,
    longitude: -3.892100,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/lagunes",
    gardeStatus: "non_confirme",
    notes: "[DEMO] Donnée de démonstration fictive — Établissement pharmaceutique agréé",
  },
  {
    name: "Pharmacie Sans Coordonnées GPS (Test Résilience)",
    phone: "+225 01 70 80 90 00",
    secondaryPhone: null,
    email: null,
    address: "Village d'Adjin, Commune de Bingerville",
    city: "Bingerville",
    country: "Côte d'Ivoire",
    latitude: null, // Test case: GPS coordinates not available, should display ⚠️ Localisation non disponible
    longitude: null,
    sourceName: "Mode Démo (Fictif)",
    sourceUrl: "https://demo.pharmaguard.ci/adjin-rural",
    gardeStatus: "non_confirme",
    notes: "[DEMO] Donnée de démonstration fictive sans coordonnées GPS pour tester les filtres de localisation",
  }
];
